insert into eateries (slug, name, branch, chain, area, category, tags, status) values
-- original 10 (with renames)
('jollibee-grove', 'Jollibee', 'Grove', 'Jollibee', 'Grove', 'Fast Food', null, 'open'),
('mcdo-vega', 'McDonald''s', 'Vega', 'McDonald''s', 'Vega', 'Fast Food', null, 'open'),
('cels-restaurant', 'Cel''s Restaurant', null, null, 'Kaliwa', 'Home Meals', null, 'open'),
('chowking-vega', 'Chowking', 'Vega', 'Chowking', 'Vega', 'Fast Food', null, 'open'),
('junes-secret-hideout', 'June''s Secret Hideout', null, null, 'Grove', 'Fast Food', null, 'open'),
('the-burger-garage', 'The Burger Garage', null, null, 'Batong Malake', 'Fast Food', array['Burger'], 'open'),
('selinas', 'Selina''s', null, null, 'Lopez Avenue', 'Restaurant', null, 'open'),
('namis-kitchen', 'Nami''s Kitchen', null, null, 'Raymundo', 'Restaurant', array['Korean'], 'open'),
('cadapan', 'Cadapan', null, null, 'Raymundo', 'Home Meals', null, 'open'),
('aling-babys', 'Aling Baby''s', null, null, 'Demarces', 'Home Meals', null, 'open'),
-- batch 2
('plato-ni-neneng', 'Plato ni Neneng', null, null, 'UPLB Campus', 'Home Meals', array['Silog'], 'open'),
('kerbys-food-hub', 'Kerby''s Food Hub', null, null, 'UPLB Campus', 'Home Meals', null, 'open'),
('ymca-canteen', 'YMCA Canteen', null, null, 'UPLB Campus', 'Home Meals', null, 'open'),
('seoul-kitchen', 'Seoul Kitchen', null, null, 'Raymundo', 'Restaurant', array['Korean'], 'open'),
('its-a-thai', 'It''s a Thai', null, null, 'Raymundo', 'Restaurant', array['Thai'], 'open'),
('janges-diner-raymundo', 'Janges Diner', 'Raymundo', 'Janges Diner', 'Raymundo', 'Home Meals', null, 'open'),
('chikin-corner', 'Chikin Corner', null, null, 'Raymundo', 'Food Stall', array['Chicken'], 'open'),
('k-go-korean-food-house', 'K-Go Korean Food House', null, null, 'Raymundo', 'Restaurant', array['Korean'], 'open'),
('k-plaza', 'K-Plaza', null, null, 'Lopez Avenue', 'Restaurant', array['Korean'], 'open'),
('doner-durum', 'Döner Dürüm', null, null, 'Vega', 'Food Stall', array['Shawarma'], 'open'),
('nings-thai', 'Ning''s Thai', null, null, 'Lopez Avenue', 'Restaurant', array['Thai'], 'open'),
('cynthias-litson-sa-banga', 'Cynthia''s Litson sa Banga', null, null, 'Raymundo', 'Home Meals', null, 'open'),
('siomai-corner', 'Siomai Corner', null, null, 'Raymundo', 'Food Stall', array['Siomai'], 'open'),
('steak2one', 'Steak2one', null, null, 'Raymundo', 'Restaurant', array['Steak'], 'open'),
('mi-pastil', 'Mi Pastil', null, null, 'Raymundo', 'Food Stall', array['Pastil'], 'open'),
('nekowave-cat-cafe', 'Nekowave Cat Cafe', null, null, 'Putho Tuntungin', 'Cafe', null, 'open'),
('starbucks-vega', 'Starbucks', 'Vega', 'Starbucks', 'Vega', 'Cafe', null, 'open'),
('cafe-de-elbi', 'Cafe de Elbi', null, null, 'Lopez Avenue', 'Cafe', null, 'open'),
('dash-espresso', 'Dash Espresso', null, null, 'Vega', 'Cafe', null, 'open'),
('badj-chicken', 'BADJ Chicken', null, null, 'Vega', 'Food Stall', array['Chicken'], 'open'),
('meisters-cafe-and-chow', 'Meister''s Cafe & Chow', null, null, 'Vega', 'Restaurant', null, 'open'),
('jollibee-junction', 'Jollibee', 'Junction', 'Jollibee', 'Junction', 'Fast Food', null, 'open'),
('big-bellys', 'Big Belly''s', null, null, 'UPLB Campus', 'Restaurant', null, 'open'),
('drip-kofi', 'Drip Kofi', null, null, 'Raymundo', 'Cafe', null, 'open'),
('the-shawarma-shack-centtromall', 'The Shawarma Shack', 'Centtromall', 'The Shawarma Shack', 'Centtromall', 'Food Stall', array['Shawarma'], 'open'),
('the-burger-grille', 'The Burger Grille', null, null, 'Vega', 'Food Stall', array['Burger'], 'open'),
('bonchon-centtromall', 'Bonchon Chicken', 'Centtromall', 'Bonchon', 'Centtromall', 'Fast Food', array['Chicken'], 'open'),
('papus-siomai-demarces', 'Papu''s Siomai', 'Demarces', 'Papu''s Siomai', 'Demarces', 'Food Stall', array['Siomai'], 'open'),
('papus-siomai-raymundo', 'Papu''s Siomai', 'Raymundo', 'Papu''s Siomai', 'Raymundo', 'Food Stall', array['Siomai'], 'open'),
('korean-top-chef', 'Korean Top Chef', null, null, 'Demarces', 'Restaurant', array['Korean'], 'open'),
('minute-burger-lopez-avenue', 'Minute Burger', 'Lopez Avenue', 'Minute Burger', 'Lopez Avenue', 'Food Stall', array['Burger'], 'open'),
('dimsum-panda-lopez-avenue', 'Dimsum Panda', 'Lopez Avenue', 'Dimsum Panda', 'Lopez Avenue', 'Food Stall', array['Chinese','Dimsum'], 'open'),
-- batch 3
('chadis-pizza', 'Chadis Pizza', null, null, 'Lopez Avenue', 'Restaurant', array['Pizza'], 'open'),
('yeonin-korean-street-food', 'Yeonin - Korean Street Food', null, null, 'Lopez Avenue', 'Food Stall', array['Korean'], 'open'),
('stable-wagyu-and-wings', 'Stable Wagyu & Wings', null, null, 'Lopez Avenue', 'Restaurant', array['Chicken'], 'open'),
('joes-inasal', 'Joe''s Inasal', null, null, 'Lopez Avenue', 'Restaurant', array['Inasal'], 'open'),
('mommy-lode-restobar', 'Mommy Lode Restobar', null, null, 'LB Square', 'Bar', null, 'open'),
('right-shot-cafe', 'Right Shot Cafe', null, null, 'Lopez Avenue', 'Cafe', null, 'open'),
('sobremesa', 'Sobremesa Restaurant & Cafe', null, null, 'Lopez Avenue', 'Cafe', null, 'open'),
('serendipity-tea-bar', 'Serendipity Tea Bar', null, null, 'Lopez Avenue', 'Cafe', array['Tea'], 'open'),
('eat-sumo-terihaus', 'Eat-sumo Terihaus', null, null, 'Lopez Avenue', 'Restaurant', array['Japanese'], 'open'),
('tastes-from-the-greens', 'Tastes from the Greens', null, null, 'Lopez Avenue', 'Cafe', null, 'open'),
('the-bean-bros', 'The Bean Bros', null, null, 'Lopez Avenue', 'Cafe', null, 'open'),
('ate-ricas-bacsilog', 'Ate Rica''s Bacsilog', null, null, 'F.O. Santos', 'Food Stall', array['Silog'], 'open'),
('milk-fridge', 'Milk Fridge', null, null, 'F.O. Santos', 'Cafe', null, 'open'),
('the-gray-area', 'The Gray Area', null, null, 'F.O. Santos', 'Cafe', null, 'open'),
('forty-thirty', 'Forty Thirty', null, null, 'F.O. Santos', 'Cafe', null, 'open'),
('tresto-pub', 'Tresto Pub', null, null, 'Umali', 'Bar', null, 'open'),
('sure-wings-lb', 'Sure Wings LB', null, null, 'Umali', 'Food Stall', array['Chicken'], 'open'),
('puesto-bar-and-lounge', 'Puesto Bar and Lounge', null, null, 'Umali', 'Bar', null, 'open'),
('pang-kang-loh', 'Pang Kang Loh', null, null, 'Umali', 'Restaurant', array['Asian'], 'open'),
('botchog-foodhub', 'Botchog Foodhub', null, null, 'Raymundo', 'Food Stall', null, 'open'),
('sadati-food-hub', 'Sadati Food Hub', null, null, 'Raymundo', 'Food Stall', null, 'open'),
('mokape-coffee', 'Mokape Coffee', null, null, 'Raymundo', 'Cafe', null, 'open'),
('aldrins-kitchen', 'Aldrin''s Kitchen', null, null, 'Raymundo', 'Food Stall', array['Chicken'], 'open'),
('breakafe', 'Breakafé', null, null, 'Raymundo', 'Cafe', array['Breakfast'], 'open'),
('ichiko-boneless-chicken', 'Ichiko Boneless Chicken', null, null, 'Raymundo', 'Food Stall', array['Chicken'], 'open'),
('big-boss-oma', 'Big Boss Oma', null, null, 'Raymundo', 'Food Stall', null, 'open'),
('chubby-habbis', 'Chubby Habbi''s Mediterranean Grill', null, null, 'Raymundo', 'Restaurant', array['Mediterranean'], 'open'),
('beanpress-cafe', 'Beanpress Cafe', null, null, 'Raymundo', 'Cafe', null, 'open'),
('wildbreads', 'Wildbreads', null, null, 'Raymundo', 'Cafe', null, 'open'),
('tropic-bowls', 'Tropic Bowls', null, null, 'Raymundo', 'Food Stall', array['Japanese'], 'open'),
('entengs-cheesy-silog', 'Enteng''s Cheesy Silog', null, null, 'Raymundo', 'Food Stall', array['Silog'], 'open'),
('siogo-siomai', 'Siogo Siomai on the Go', null, null, 'Raymundo', 'Food Stall', array['Siomai'], 'open'),
('sweet-tooth', 'Sweet Tooth', null, null, 'Raymundo', 'Cafe', null, 'open'),
('favor-cafe', 'Favor Cafe', null, null, 'Raymundo', 'Cafe', null, 'open'),
('h2-cafe', 'H2 Cafe', null, null, 'Raymundo', 'Cafe', null, 'open'),
('yakiyaki', 'Yakiyaki', null, null, 'Raymundo', 'Food Stall', array['Japanese'], 'open'),
('we-deliver-uplb', 'We Deliver', 'UPLB Campus', 'We Deliver', 'UPLB Campus', 'Food Stall', array['Breakfast'], 'open'),
('pickup-coffee-uplb', 'Pickup Coffee', 'UPLB Campus', 'Pickup Coffee', 'UPLB Campus', 'Cafe', null, 'open'),
('kwatogs', 'Kwatogs', null, null, 'Junction', 'Restaurant', null, 'open')
on conflict (slug) do nothing;